--this script initiates db for h2 db (used in test profile)
insert into user (id, account_status, email, first_name, last_name) values (1, 'CONFIRMED', 'john@domain.com', 'John', 'Steward')
insert into user (id, account_status, email, first_name, last_name) values (2, 'CONFIRMED', 'test1@domain.com', 'Test1', 'Steward')
insert into user (id, account_status, email, first_name, last_name) values (3, 'CONFIRMED', 'test2@domain.com', 'Test1', 'Steward')
insert into user (id, account_status, email, first_name, last_name) values (4, 'REMOVED', 'test3@domain.com', 'Test1', 'Steward')
insert into user (id, account_status, email, first_name, last_name) values (5, 'NEW', 'test4@domain.com', 'Test1', 'Steward')
insert into user (id, account_status, email, first_name, last_name) values (6, 'CONFIRMED', 'test5@domain.com', 'Test1', 'Steward')
insert into user (id, account_status, email, first_name) values (null, 'NEW', 'brian@domain.com', 'Brian')
insert into blog_post (id, entry, user_id) values (1, 'Test post', 1)
insert into blog_post (id, entry, user_id) values (2, 'Test post2', 1)
insert into blog_post (id, entry, user_id) values (3, 'Test post3', 4)
insert into blog_post (id, entry, user_id) values (4, 'Test post4', 6)
insert into like_post (id, post_id, user_id) values (1, 2, 2)  
